# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Project Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    name: Build scheme
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pod install --repo-update
        shell: bash
      - name: Build
        run: |
          xcodebuild -workspace MoveeApp.xcworkspace -scheme MoveeApp clean build -sdk iphoneos -configuration Development CODE_SIGNING_ALLOWED=No
